// Generated by https://quicktype.io

import { ICategory } from "../categories/categories-response";

export interface IProductsResponse {
    data: IProduct[];
}

export interface IProduct {
    id:          string;
    name:        string;
    slug:        string;
    stock:       number;
    price:       number;
    description: string;
    category:    ICategory;
    images:      Image[];
}

interface Image {
    id:  number;
    url: string;
}
