// Generated by https://quicktype.io

export interface ICategoriesResponse {
    data: ICategory[];
}

export interface ICategory {
    id:          string;
    name:        string;
    slug:        string;
    image:       string;
    description: string;
}
